### ISSUE TITLE
How to enable buttons?

### ISSUE THREAD

**Issue by xturkix** [qweryty/image-ai-utils-krita#2]
Hi, thank you for the amazing add-on. I just wanted to know, how do I enable the "Upscale", "GFPGAN", "Make Tilable" and "Quick Mask" buttons? they are greyed out for me in the add-on panel.

**Comment by qweryty** [comment]
Those features are not implemented yet. They probably will be available in the next release.

**Comment by xturkix** [comment]
Thank you for the response. Keep up the good work. If I may suggest also adding out-painting.
